4_create_load_balancer.sh, Dockerfile.test, Jenkinsfile, README.md, build/haproxy/docker-entrypoint.sh, haproxy/update_haproxy.sh, secrets.yml
=> Remove 3.3 OpenShift testing

0_check_dependencies.sh, 1_create_conjur_namespace.sh, 3_deploy_conjur_cluster.sh, 4_create_load_balancer.sh, 7_configure_followers.sh, 8_print_config.sh, README.md, bootstrap.env, delete-deployments.sh, foo.sh, kubernetes/README.md, kubernetes/_minikube-boot.env, kubernetes/_minikube-start.sh, kubernetes/haproxy-conjur-master.yaml, openshift/README.md, openshift/_minishift-boot.env, openshift/_minishift-start.sh, openshift/conjur-follower.yaml, openshift/haproxy-conjur-master.yaml, start, stop, utils.sh
updated README in openshift subdirectory documented minishift startup process
changed ADMIN_USERNAME environment variables to be more descriptive and updated scripts.
=> Deploy scripts work with minikube / minishift

README.md, openshift/_minishift-boot.env
- Update README to point to correct file
- Add command to set Docker registry path
=> Update minishift boot file

0_check_dependencies.sh
Update the script to check dependencies to verify that the Conjur version of
the appliance matches the specified CONJUR_VERSION
=> Validate Conjur version before continuing

README.md, bootstrap.env
Connected to conjurinc/appliance#602
Updates bootstrap.env to be simpler, so we can refer to it as a resource in our documentation.
=> Simplify bootstrap.env for follower-only flow

.gitignore, 0_check_dependencies.sh, 1_prepare_conjur_namespace.sh, 2_prepare_docker_images.sh, 4_deploy_conjur_followers.sh, 6_configure_master.sh, 7_configure_standbys.sh, 8_configure_followers.sh, README.md, _save_server_cert.sh, bootstrap.env, build/seed-fetcher/Dockerfile, build/seed-fetcher/build.sh, build/seed-fetcher/get-seedfile.sh, build/seed-fetcher/start-follower.sh, dev-bootstrap.env, kubernetes/conjur-follower.yaml, openshift/conjur-cli.yml, openshift/conjur-follower.yaml, start, test.sh
We added container that will retrieve seed file from Conjur
In order to be able to auto scale followers in OpenShift we need to retrieve the seed file each time
=> Fetch seedfile in deploy

build/seed-fetcher/get-seedfile.sh
`follower-hostname` has been changed to `follower-hostnames`.
=> Update post parameters to seed service

3_deploy_conjur_master_cluster.sh, Jenkinsfile, kubernetes/conjur-follower.yaml, openshift/conjur-follower.yaml, stop, test.sh
+ increase readinessProbe timeoutSeconds
+ wait_for_conjur forever instead of 300s
=> increase readinessProbe timeoutSeconds and wait_for_conjur time

0_check_dependencies.sh, 1_prepare_conjur_namespace.sh, 3_deploy_conjur_master_cluster.sh, Jenkinsfile, secrets.yml, start, stop, test_oc_entrypoint.sh
Obviously please squash lol
- Update the openshift username secret value
- Switch the wait from infinite to 10m
- Drop the v4 tests
- Add Openshift 3.9, 3.10, and 3.11 tests/secrets
- Drop the master relaunch (to match the GKE tests)
=> Add OC tests back into the mix

6_configure_master.sh, relaunch_master.sh
This PR updates the DAP master configuration scripts to include EULA acceptance.
=> Add EULA acceptance to master configuration

README.md
Update Readme to include the docker version that suites minishift and seed fetcher
=> Update Readme docker version

6_configure_master.sh
The start currently includes a 10 second sleep to wait for the Master to be ready, rather than using the Master's health to check for readiness. These leads to occasional failures when the master isn't ready in that span of time.
This PR changes that wait to be a health check loop to wait until the Master is ready to handle requests.
=> Add a wait loop for DAP master to be ready

6_configure_master.sh, 7_configure_standbys.sh, relaunch_master.sh, utils.sh
In case the CONJUR_LOG_LEVEL environment variable is provided,
we set it in the DAP master & follower
=> Set CONJUR_LOG_LEVEL if env var provided

2_prepare_docker_images.sh, 3_deploy_conjur_master_cluster.sh, 4_deploy_conjur_followers.sh, 6.5_configure_cli_pod.sh, CONTRIBUTING.md, oss/conjur-cluster.yaml, oss/conjur-postgres.yaml, oss/nginx_base/Dockerfile, oss/nginx_base/proxy/default.conf, oss/nginx_base/proxy/ssl.conf, start, test.sh, test_gke_entrypoint.sh, test_oc_entrypoint.sh
- Testing secrets provider worked with specific branch to run oss environment so this ticket implement first phase of oss environment for testing (second phase is working with helm ) . 
Connected to #135
=> Add oss env for testing

test_gke_entrypoint.sh, test_oc_entrypoint.sh
Fix testing log collection on GKE and adding get events on oc and GKE
Connected to #139
=> Fix testing log collection

3_deploy_conjur_master_cluster.sh, test_gke_entrypoint.sh
- Print GKE version
- Add minor change for GKE on oss, we will not init conjur before the container is raedy
=> Minor fix on GKE for oss + get GKE version

2_prepare_docker_images.sh
This log can help knowing which Conjur image is used (especially if the
local image was taken)
=> Echo Conjur oss image name

1_prepare_conjur_namespace.sh, 3_deploy_conjur_master_cluster.sh, 4_deploy_conjur_followers.sh, Dockerfile.test, Jenkinsfile, openshift/conjur-cli.yml, openshift/conjur-cluster-stateful.yaml, openshift/conjur-cluster.yaml, openshift/conjur-follower.yaml, secrets.yml, start, stop, utils.sh
Adding support for deployment of OCP 4.3
=> Support OC 4.3 delpoyment

3_deploy_conjur_master_cluster.sh, 4_deploy_conjur_followers.sh, utils.sh
Bug fix: Verify if TEST_PLATFORM exists before calling it
Connected to #[relevant GitHub issues, eg 76]
=> Verify if TEST_PLATFORM exists before calling it

3_deploy_conjur_master_cluster.sh, 4_deploy_conjur_followers.sh
Logic fix in the test platform condition
- _What's changed? Why were these changes made?_
- _How should the reviewer approach this PR, especially if manual tests are required?_
- _Are there relevant screenshots you can add to the PR description?_
Connected to #[relevant GitHub issues, eg 76]
=> Fix logic in test platform

4_deploy_conjur_followers.sh, README.md, oss/conjur-postgres.yaml
Update all mentions of postgres 9.4 and update to 10. Version 9.4 is currently EOL
#154
=> update Postgres database to version 10

Jenkinsfile, secrets.yml
=> Use new swappable conjurops OpenShift variables

oss/nginx_base/Dockerfile
Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
Updates the nginx base image
=> Update nginx base image to 1.21.6

README.md, openshift/README.md, openshift/minishift-start.sh
Some file names were changed in #42 but were never updated in the README files.
Updated READMEs to point to correct file names
N/A
CHANGELOG update
changes, or
=> Update file names in readmes for openshift
