cyberark/kubernetes-conjur-deploy

1_create_conjur_namespace.sh, kubernetes/conjur-authenticator-role.yaml, openshift/conjur-authenticator-role.yaml
To avoid collisions in conjur-authenticator ClusterRole deletion, the
namespace will be appended to the ClusterRole
The current `5.0-stable` appliance image is broken for k8s, so this was built pinned to `5.1.2` and had a green build.
=> Append namespace to authenticator ClusterRole

secrets.yml
The cluster was upgraded to v1.9.7, and this PR updates kubectl used in the
tests to the same version.
=> Update kubectl used in test scripts

start
If this value is not defaulted, there's a high risk that it will fail
since the new env files do not have it set by default.
=> Fixed issues with DEPLOY_MASTER_CLUSTER not being checked properly

kubernetes/conjur-follower.yaml, openshift/conjur-follower.yaml
Update the manifests to include readiness probes for the Conjur followers
Tested in OpenShift 3.9
Connected to #41
=> Add readiness probes to follower manifests

start
This script is only applicable to master cluster deployment so it should
not execute otherwise.
=> Remove buggy cluster info printing when deploying follower

3_deploy_conjur_master_cluster.sh, 4_deploy_conjur_followers.sh, 5_create_load_balancer.sh, delete-deployments.sh, kubernetes/haproxy-conjur-master.yaml, openshift/conjur-follower.yaml, openshift/haproxy-conjur-master.yaml, relaunch_master.sh
1. StatefulSets timeout on volume claims in OpenShift 3.9; resolved by only using DeploymentConfigs for OpenShift.
2. DeploymentConfigs default to 0 replicas so it's necessary to have `CONJUR_FOLLOWER_COUNT defaulting` to 1
=> fix: works in openshift

kubernetes/conjur-authenticator-role-binding.yaml, openshift/conjur-authenticator-role-binding.yaml
conjur-authenticator-role-binding.yaml files was missing for both kubernetes and openshift
=> Added missing files for deploy scripts

openshift/conjur-cli.yml
This change wasn't needed and possibly broke master deployment of the
k8s-conjur-demo.
Connected to: https://github.com/conjurinc/appliance/issues/772
=> Reverted CLI change that hard-coded the CLI version image

start
Made the running of the stop script optional
In our documentation we create service accounts in conur namespace before running this scripts so if the namespace is being purged all the service accounts that were created before are deleted
=> Added default value for variable STOP_RUNNING_ENV

6_configure_master.sh
Evoke has removed the ability to add IP entries to certificate SAN
fields since they were already prefixed with `DNS:` and should not have
worked. By doing this, our code here broke since it was stuffing and IP
address into the master altname which should not have worked at all.
This change removes that IP from the altnames to make things work again.
=> Removed addition of IPs to DNS SAN entries on master cluster config

stop
By default, we don't define OPENSHIFT_USERNAME in non-Jenkins
deployments so this variable will fail running of the code. This change
ensures that `./stop` can handle this missing variable just like the
`./start` script.
=> Fix missing variable in ./stop script

8_configure_followers.sh, README.md
This allows clusters that are using master key encryption to optionally provide the key file to be used by the follower.
=> Add encryption key checking and use when starting follower

stop
The CI pipeline currently leaves the cluster role intact after cleaning up,
leaving unused cluster roles dangling in the platform environment. This change
ensures that they are cleaned up after the test run.
=> ClusterRole is deleted on cleanup

8_configure_followers.sh
Old code in some cases would get into configuration of the follower
without a CONJUR_DATA_KEY defined and bash would consider that to be an
error and return from the function without configuring the follower.
This change ensures that we go through the follower configuration even
if that variable is undefined (which is a common case in follower
deployment).
**Note: This fix does not fully solve the problem but it does get us to the next one!**
Connected to #80 
Connected to #76
=> Fix issues with follower deployments variable evaluation

Dockerfile.test
`wget` was flooding the output with progress update from the `oc` tool
download. We now squelch the output of it with `--no-verbose` flag.
=> Reduce noise from building test image

Dockerfile.test
This should reduce our logs significantly even more as we won't dump
out the progress updates to jenkins logs.
=> Reduce noise from downloading `kubectl` in test images

Jenkinsfile, secrets.yml
Somewhere between Summon v0.6.6 and Summon v0.8.0 it became a requirement
that Summon vars **must** either be in a specific environment **or** in a `common`
section when using Summon environments.
This commit updates the secrets.yml for this project so that it conforms with this new
standard, to facilitate bumping the Summon version in our pipelines.
=> Move common Summon vars into common section

4_deploy_conjur_followers.sh, README.md, kubernetes/conjur-follower.yaml, openshift/conjur-follower.yaml
In OpenShift 3.9, ephemeral disk storage cannot be configured per-pod or per-container, only in the global docker daemon settings, with a default of 10GB.  In OpenShift 3.10 and 3.11, this feature is experimental and not enabled by default.  Because of the potentially large size of log audit and nginx log file sizes, this uses the emptydir host volume mounts to prevent the container from running out of storage under loads typically seen during testing or longer running followers.
=> Add host mount via emptydir volumes for postgres, conjur and nginx logs

kubernetes/conjur-authenticator-role.yaml, kubernetes/conjur-cli.yml, kubernetes/conjur-cluster-stateful.yaml, kubernetes/conjur-cluster.yaml, kubernetes/conjur-follower.yaml, openshift/conjur-cli.yml, openshift/conjur-cluster-stateful.yaml, openshift/conjur-cluster.yaml, openshift/conjur-follower.yaml
This impacts
- ClusterRole (v1 support in k8s 1.8 -
https://kubernetes.io/blog/2017/10/using-rbac-generally-available-18/)
- Deployment (officially removed support for v1beta1 in k8s 1.16 -
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/)
- StatefulSet (officially removed support for v1beta1 in k8s 1.16 -
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/)
=> Updates K8s API versions to v1 from v1beta1

kubernetes/conjur-follower.yaml, openshift/conjur-follower.yaml
The conjurdemos/kubernetes-conjur-demo repo CI is currently failing on that repo's master. Here's a recent failure:
https://jenkins.conjur.net/job/conjurdemos--kubernetes-conjur-demo/job/master/373/
The console output from one test case shows this error:
```
09:54:10  + ./4_store_conjur_cert.sh
09:54:10  ++++++++++++++++++++++++++++++++++++++
09:54:10
09:54:10  Storing Conjur cert for test app configuration.
09:54:10
09:54:10  ++++++++++++++++++++++++++++++++++++++
09:54:10  Retrieving Conjur certificate.
09:54:10  No resources found.
09:54:11  Value added
09:54:11  Value added
09:54:11  No resources found.
09:54:11  error: expected 'exec POD_NAME COMMAND [ARG1] [ARG2] ... [ARGN]'.
09:54:11  POD_NAME and COMMAND are required arguments for the exec command
09:54:11  See 'oc exec -h' for …
```
=> Restore role follower label in follower pod templates

3_deploy_conjur_master_cluster.sh
Increase Conjur pods to launch timeout. It exist already in master and now added to specific tag (deploy-oss-tag) since we are working with this tag on secrets-provider-for-k8s.
This fix suppose to handle 30% of our failures on secrets-provider-for-k8s.
=> increasing conjur timeout

secrets.yml
When the client version is too far behind the server version, the following error can result: 
```
Error from server (NotFound): the server could not find the requested resource
```
This PR updates the client version to avoid the error. 
Related: conjurinc/ops#572
=> Update kubectl to latest stable

0_check_dependencies.sh, 3_deploy_conjur_master_cluster.sh, 6_configure_master.sh, CONTRIBUTING.md, Jenkinsfile, README.md, test.sh, utils.sh
Since this repo will almost never be used for v4 deployment, all the
special logic we had for it are rather useless, especially given the
fact that the tests for v4 don't run. This should make our code sturdier
and cleaner.
=> 113 Removed out any references of Conjur v4 (other than README)

4_deploy_conjur_followers.sh, bootstrap.env, kubernetes/conjur-follower.yaml, openshift/conjur-follower.yaml
The value of `CONJUR_AUTHN_LOGIN` in the scripts was hard-coded to a value that is different from the one stated in the docs. This PR makes the value of `CONJUR_AUTHN_LOGIN` configurable so it can match the value in the docs.
This [doc bug](https://github.com/cyberark/conjur-docs/issues/983) will complete this PR as the docs will change to reflect the correct flow.
Connected to cyberark/conjur-docs#983
=> Fix conjur authn login

bootstrap.env, start
The default value of STOP_RUNNING_ENV is set to 'true' so in case a customer
misses it, and has already created resources in their env, it will be deleted
without them noticing.
This commit adds a section to `bootstrap.env` that explains its meaning and also
echos that we are stopping the environment before doing so.
=> Emphasize the meaning of STOP_RUNNING_ENV

6_configure_master.sh
During Master configuration, we create an OpenShift route that exposes the Master outside of the cluster. However, if you attempt to use this route w/ the CLI you will get a certificate error because the route domain is not listed in the Master altnames on the cert.
This PR adds the route domain to the Master cert altnames and also modifies the route to use the `conjur-master-ext` service which was intended to be used to expose the Master externally.
N/A
=> Add external domain to master altnames

1_prepare_conjur_namespace.sh, 4_deploy_conjur_followers.sh, kubernetes/conjur-authenticator-role-binding.yaml, openshift/conjur-authenticator-role-binding.yaml
The ClusterRoleBinding was created only after the followers were deployed
but there's no reason that it will be created then and not right after we
create the ClusterRole.
Furthermore, it was created for a new service-account that was named `conjur`
and was never used. This means that it didn't do anything and the only reason why 
we didn't see issues is that the docs tell customers to do it manually (while there's
no reason they should) and consuming projects (e.g `secrets-provider-for-k8s`, `conjur-authn-k8s-client`)
created the correct ClusterRoleBinding on their own.
=> Create ClusterRoleBinding as part of namespace preparation

8_configure_followers.sh, utils.sh
We are setting the CONJUR_LOG_LEVEL value to the DAP
master and stanby if it's present but we should also do
it for the follower.
=> Set CONJUR_LOG_LEVEL to DAP follower if present

4_deploy_conjur_followers.sh
This PR is meant to apply oc cli api changes from version 3.11 to version 4.X in the secrets add section.
No related issue.
Tested locally with oc version:
Client Version: 4.4.11
Server Version: 4.3.21
Kubernetes Version: v1.16.2
Old API reference: https://docs.openshift.com/enterprise/3.0/dev_guide/image_pull_secrets.html
New API reference: https://docs.openshift.com/container-platform/4.4/openshift_images/managing_images/using-image-pull-secrets.html
=> DockerPullSecret: adapt oc 4.X api changes

0_check_dependencies.sh, 1_prepare_conjur_namespace.sh, 2_prepare_docker_images.sh, CONTRIBUTING.md, README.md, dev-bootstrap.env, utils.sh
We are pursuing an effort to build a local dev environment so that instead of pushing to a remote K8s cluster, developers can deploy the cluster locally with Docker desktop
- Add dev checks to block from unnecessary code from running
- Create separate bootstrap.env file for local development
TODO:
Feedback from: https://github.com/cyberark/kubernetes-conjur-deploy/pull/131/files
=> WIP: Add logic to support local dev environment

CONTRIBUTING.md
There is a misspell in contribution docs inaccurately listing how much memory is needed to deploy conjur in a local k8s cluster
Was: 
1. Click on "Advanced" and slide the "Memory" bar to 4
Should be:
1. Click on "Advanced" and slide the "Memory" bar to 6
=> Fix memory limit in documentation

Jenkinsfile, secrets.yml
When infra publish that the static claster of 4.3-fips is available with variables defined in this secrets.yaml - this build and PR should pass & marged 
- _What's changed? Why were these changes made?_
- _How should the reviewer approach this PR, especially if manual tests are required?_
- _Are there relevant screenshots you can add to the PR description?_
Connected to #[relevant GitHub issues, eg 76]
=> Support OC 4.3-FIPS

3_deploy_conjur_master_cluster.sh
The Secrets Provider is experiencing constant failures when deploying Conjur OSS. This was happening because we were randomly generating characters for the PG password, giving us invalid PG URIs. This PR fixes this by providing a constant postgres password.
Connected to -
=> Update PG password to be a constant value

test.sh
Make CONJUR_APPLIANCE_IMAGE tag configurable
Allow users of this repo to use a different tag than `5.0-stable`.
This can be done by setting CONJUR_APPLIANCE_IMAGE_TAG in the env
running the `start` script
=> Make CONJUR_APPLIANCE_IMAGE tag configurable

6_configure_master.sh, secrets.yml, test.sh
- A set of pre-generated dhparams are pulled from Conjur and copied into the master appliance image so we don't waste time/compute generating a new set. This should address stability issues in clusters running on OCP/k8s using this repo.
**NOTE:** This was completed to the best of my knowledge but this is a beast of a repo. Someone with broad knowledge of it should conduct the review to evaluate any usage paths this may disrupt.
=> Add dhparams to master clusters

secrets.yml
Adds summon environment for the openshift 3.11 cluster in AWS DEV
This allows developers to use k-c-d with the dev cluster without modifying secrets.yml.
This is important as developers no longer have acecss to the ci clusters.
Related: conjurinc/ops#692
=> Add openshift 3.11 dev environment

openshift/conjur-authenticator-role.yaml
This change adds permissions to get and list `DeploymentConfigs`
resources on OpenShift. This will allow the authn-k8s authenticator
to authenticate based on a client's DeploymentConfig on an
OpenShift platform.
This change adds permissions to get and list `DeploymentConfigs`
resources on OpenShift. This will allow the authn-k8s authenticator
to authenticate based on a client's DeploymentConfig on an
OpenShift platform.
Resolves #157
=> Adds RBAC permission for OpenShift DeploymentConfigs

Jenkinsfile, secrets.yml
Our new OCP 4.3 cluster is FIPS-compliant so we don't need to run the tests
explicitly on another OCP 4.3 FIPS-compliant cluster
=> Remove explicit tests for OCP 4.3 FIPS

2_prepare_docker_images.sh, 3_deploy_conjur_master_cluster.sh, test_gke_entrypoint.sh, test_oc_entrypoint.sh, utils.sh
The command "new-dockercfg" is deprecated, and it is best
to use `oc create secret` instead.
This [`kubernetes-conjur-demo` build](https://jenkins.conjur.net/blue/organizations/jenkins/conjurdemos--kubernetes-conjur-demo/detail/use-create-secret/3/pipeline/) verifies this change.
=> Create dockerpull secret using oc create secret

stop
This change adds a workaround for this OpenShift 4.3 bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1798282
Without this fix, deleting a namespace on OpenShift 4.3 could result
in indefinite hanging due to finalizers that are not being
deleted from services in the namespace.
NOTE: Jenkins tests are currently failing for Current OpenShift on AWS.
These failures are apparently unrelated to the fix proposed here since
they are also occuring on the master branch.
Resolves #167
=> Eliminates hanging when deleting namespace for OpenShift 4.3

6_configure_master.sh, 9_print_cluster_info.sh, README.md, kubernetes/conjur-cluster-ext-service.yaml, openshift/conjur-cluster-ext-service.yaml, openshift/conjur-cluster-service.yaml, stop
There is a bug in OpenShift 4.3 that results in it being unable to tear down ELBs that were created from a service defined as `type: LoadBalancer`.  The current `stop` script bypasses the issue by removing finalizers, but that results in ELBs persisting after the run.  To fix this, the external load balancers need to not be created for 4.3 clusters.  To handle this, `kubernetes-conjur-deploy` will no longer deploy external facing load balancers.  The yaml config for kubernetes and openshift is included should someone want to deploy it manually.
-  This no longer deploys external facing load balancers
-  This removes special casing for OC 4.3 and enforces a timeout
on deleting the namespace. If a namespace fails to be deleted within
5 minutes it will result in the script exiting with an …
=> Protect 43 teardown

2_prepare_docker_images.sh
Developers should be able to spin up a dev environment on their local machines. Currently this doesn't work because the ImagePullPolicy is set to 'Never' in dev mode, which will cause the script to fail when trying to create a postgres instance because the script doesn't pull the postgres image beforehand.
To reproduce issue:
Clone the secrets-provider-for-k8s repo and run `./bin/start --dev --oss`. The script will clone the kubernetes-conjur-deploy repository and attempt to deploy a local cluster, but will timeout when it tries to deploy conjur-postgres. Checking the kubernetes logs, you'll see "Container image "postgres:10" is not present with pull policy of Never".
You can confirm the fix by editing the `git clone git@github.com:cyberark/kubernetes-conjur-deploy` line to add `-b …
=> Fix for running with local environment

openshift/conjur-authenticator-role.yaml
```
Using non-groupfied API resources is deprecated and will be removed in a future release, update apiVersion to "authorization.openshift.io/v1" for your resource
```
This deprecation has started causing failures in CI for cyberark/secrets-provider-for-k8s:
```
error: resource mapping not found for name: "conjur-authenticator-conjur-572ae17d-d" namespace: "" from "STDIN": no matches for kind "ClusterRole" in version "v1"
```
Updates ClusterRole apiVersion from ungrouped `v1` to grouped `rbac.authorization.k8s.io/v1`
N/A
*At least 1 todo must be completed in the sections below for the PR to be
merged.*
CHANGELOG update
changes, or
=> Update ClusterRole apiVersion

7_configure_standbys.sh, 8_configure_followers.sh, CONTRIBUTING.md
Remove warning:
> kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
Update `kubectl exec` command syntax to put a `--` before the command.
N/A
CHANGELOG update
changes, or
=> Update kubectl exec syntax

0_check_dependencies.sh, 2_prepare_docker_images.sh, 3_deploy_conjur_master_cluster.sh, 6.5_configure_cli_pod.sh, 6_configure_master.sh, CONTRIBUTING.md, Jenkinsfile, README.md, bootstrap.env, dev-bootstrap.env, exec-into-cli.sh, kubernetes/test-curl.yml, openshift/test-curl.yml, test.sh, test_gke_entrypoint.sh, utils.sh
Update scripts to use Conjur CLI v8.0.
- Updated `2_prepare_docker_images.sh` script to use version 8 of the Conjur CLI image.
- Update CLI commands to use new syntax
- Add new test-curl pod to test master readiness since the new cli container doesn't contain curl
- Remove support for Conjur v4 in all scripts
CyberArk internal issue ID: ONYX-33379
CHANGELOG update
changes, or
=> Use Conjur CLI v8.0

2_prepare_docker_images.sh
This PR addresses issue with failing pipelines that uses this repository. Currently it is pulling dap-seedfetcher with latest tag that is 5 months old. Instead it should pull the image with tag edge that is up to date with other repositories (such as appliance). It is believed to be the main issue of failing pipelines such as authn-k8s-client.
*Describe how the desired outcome above has been achieved with this PR. In
particular, consider:*
- _What's changed? Why were these changes made?_
- _How should the reviewer approach this PR, especially if manual tests are required?_
- _Are there relevant screenshots you can add to the PR description?_
Resolves #[relevant GitHub issue(s), e.g. 76]
CyberArk internal issue ID: [insert issue ID]
*At least 1 todo must be completed in the sections below …
=> Pull seed-fetcher image with tag edge rather than latest

oss/nginx_base/Dockerfile
Remove base images that contain vulnerable versions of libwebp to remove any possibility of CVE-2023-4863/CVE-2023-5129
- Upgraded nginx base image in oss/nginx_base to latest version (1.25.2)
CyberArk internal issue ID: CNJR-1709
=> Upgrade nginx-base base image to nginx:1.25.2
